kind: pipeline
name: default

steps:

-name: setup
  setup:
    image: docker:git
    commands:
      - git clone https://bia-christian.de/gitea/choener/Lib-DPutils.git
      - git clone https://bia-christian.de/gitea/choener/Lib-OrderedBits.git

- name: build
  image: haskell
  volumes:
  - name: cache
    path: /tmp/cache
  commands:
  - mkdir -p /tmp/cache/.cabal
  - ln -s /tmp/cache/.cabal /root/.cabal
  - ls
  - ls ../
  - cabal update
  - cabal new-build

- name: test
  image: haskell
  volumes:
  - name: cache
    path: /tmp/cache
  commands:
  - mkdir -p /tmp/cache/.cabal
  - ln -s /tmp/cache/.cabal /root/.cabal
  - cabal new-test

- name: haddock
  image: haskell
  volumes:
  - name: cache
    path: /tmp/cache
  commands:
  - mkdir -p /tmp/cache/.cabal
  - ln -s /tmp/cache/.cabal /root/.cabal
  - cabal new-haddock

volumes:
- name: cache
  host:
    path: /home/choener/drone

